version: '3.8'

services:
  nestdb:
    container_name: nestdb
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nest
    networks:
      - nestnetwork
      
networks:
  nestnetwork: